//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Units/PlayerInput/PlayerInputControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace RPG.Units.Player
{
    public partial class @PlayerInputControl: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputControl"",
    ""maps"": [
        {
            ""name"": ""MoveMap"",
            ""id"": ""6c14bc16-f7fe-4ce2-a555-8ba3a0d9c780"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""da6151f0-7d7f-4aa4-951d-93f6f5730e94"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f7c7db99-282f-4959-8c85-c6db54eeb7cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RHandAttack"",
                    ""type"": ""Button"",
                    ""id"": ""5b740a7c-a74d-476a-b3f2-d6168c506dce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LHandAttack"",
                    ""type"": ""Button"",
                    ""id"": ""3fc50f0e-4e07-48e5-b0a8-a16e8ab5a260"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delta"",
                    ""type"": ""Value"",
                    ""id"": ""c80a34eb-0634-4857-8344-83e108487d0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""97dffbea-8bc5-4879-b877-83d259e25416"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""fcb5ea1d-d3ec-48ea-8e96-ba3a08ad6275"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""3a3d1610-86cb-458b-83a7-42c124c70afe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3a84fbdd-928a-43c1-93c9-bde53e1a64c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c92efeaa-e834-4abd-8f5b-51507ee1b760"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""123e96ce-6815-46fe-a1d8-21262fa86c9d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6227ee3d-cd51-4dbc-b40a-60a0d0475867"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4efcb4c1-e1e9-409e-908f-c2cc9a0ceb65"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""525e3868-cc54-45aa-8c76-4cd1c9562e06"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RHandAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d35db2ba-3b03-4fde-8c67-e74c7ccf130b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LHandAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f51e45f-15dc-42ac-bec1-5e42d87c90a2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4baada5b-ca64-493b-a1a2-295e281a5103"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cc56988-fe09-4f54-ab8a-63029343c9af"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SwitchWeapon"",
            ""id"": ""198b4178-6d5d-4db1-8037-e5d31666b05a"",
            ""actions"": [
                {
                    ""name"": ""FirstSlot"",
                    ""type"": ""Button"",
                    ""id"": ""dd6c0106-9379-4715-9ece-45e493381342"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSlot"",
                    ""type"": ""Button"",
                    ""id"": ""7606c785-2e7a-42d3-a021-b723e20b4e10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSlot"",
                    ""type"": ""Button"",
                    ""id"": ""9556a3d6-51cc-4a4a-aa19-4fc137bf7fef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""disarm"",
                    ""type"": ""Button"",
                    ""id"": ""fde14417-09ee-4d7d-ab61-f93480692f72"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9ba1ee3b-76e4-4166-9531-599e4ce88bbc"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3848fee9-cdfa-470d-8d80-c7946046e86a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d844cb2-79b6-41ec-a4ce-923f51533a79"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fc20785-b5cb-4fda-b5da-b0d45ddf9959"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""disarm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // MoveMap
            m_MoveMap = asset.FindActionMap("MoveMap", throwIfNotFound: true);
            m_MoveMap_Move = m_MoveMap.FindAction("Move", throwIfNotFound: true);
            m_MoveMap_Jump = m_MoveMap.FindAction("Jump", throwIfNotFound: true);
            m_MoveMap_RHandAttack = m_MoveMap.FindAction("RHandAttack", throwIfNotFound: true);
            m_MoveMap_LHandAttack = m_MoveMap.FindAction("LHandAttack", throwIfNotFound: true);
            m_MoveMap_Delta = m_MoveMap.FindAction("Delta", throwIfNotFound: true);
            m_MoveMap_Crouch = m_MoveMap.FindAction("Crouch", throwIfNotFound: true);
            m_MoveMap_Sprint = m_MoveMap.FindAction("Sprint", throwIfNotFound: true);
            // SwitchWeapon
            m_SwitchWeapon = asset.FindActionMap("SwitchWeapon", throwIfNotFound: true);
            m_SwitchWeapon_FirstSlot = m_SwitchWeapon.FindAction("FirstSlot", throwIfNotFound: true);
            m_SwitchWeapon_SecondSlot = m_SwitchWeapon.FindAction("SecondSlot", throwIfNotFound: true);
            m_SwitchWeapon_ThirdSlot = m_SwitchWeapon.FindAction("ThirdSlot", throwIfNotFound: true);
            m_SwitchWeapon_disarm = m_SwitchWeapon.FindAction("disarm", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // MoveMap
        private readonly InputActionMap m_MoveMap;
        private List<IMoveMapActions> m_MoveMapActionsCallbackInterfaces = new List<IMoveMapActions>();
        private readonly InputAction m_MoveMap_Move;
        private readonly InputAction m_MoveMap_Jump;
        private readonly InputAction m_MoveMap_RHandAttack;
        private readonly InputAction m_MoveMap_LHandAttack;
        private readonly InputAction m_MoveMap_Delta;
        private readonly InputAction m_MoveMap_Crouch;
        private readonly InputAction m_MoveMap_Sprint;
        public struct MoveMapActions
        {
            private @PlayerInputControl m_Wrapper;
            public MoveMapActions(@PlayerInputControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_MoveMap_Move;
            public InputAction @Jump => m_Wrapper.m_MoveMap_Jump;
            public InputAction @RHandAttack => m_Wrapper.m_MoveMap_RHandAttack;
            public InputAction @LHandAttack => m_Wrapper.m_MoveMap_LHandAttack;
            public InputAction @Delta => m_Wrapper.m_MoveMap_Delta;
            public InputAction @Crouch => m_Wrapper.m_MoveMap_Crouch;
            public InputAction @Sprint => m_Wrapper.m_MoveMap_Sprint;
            public InputActionMap Get() { return m_Wrapper.m_MoveMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MoveMapActions set) { return set.Get(); }
            public void AddCallbacks(IMoveMapActions instance)
            {
                if (instance == null || m_Wrapper.m_MoveMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MoveMapActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @RHandAttack.started += instance.OnRHandAttack;
                @RHandAttack.performed += instance.OnRHandAttack;
                @RHandAttack.canceled += instance.OnRHandAttack;
                @LHandAttack.started += instance.OnLHandAttack;
                @LHandAttack.performed += instance.OnLHandAttack;
                @LHandAttack.canceled += instance.OnLHandAttack;
                @Delta.started += instance.OnDelta;
                @Delta.performed += instance.OnDelta;
                @Delta.canceled += instance.OnDelta;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
            }

            private void UnregisterCallbacks(IMoveMapActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @RHandAttack.started -= instance.OnRHandAttack;
                @RHandAttack.performed -= instance.OnRHandAttack;
                @RHandAttack.canceled -= instance.OnRHandAttack;
                @LHandAttack.started -= instance.OnLHandAttack;
                @LHandAttack.performed -= instance.OnLHandAttack;
                @LHandAttack.canceled -= instance.OnLHandAttack;
                @Delta.started -= instance.OnDelta;
                @Delta.performed -= instance.OnDelta;
                @Delta.canceled -= instance.OnDelta;
                @Crouch.started -= instance.OnCrouch;
                @Crouch.performed -= instance.OnCrouch;
                @Crouch.canceled -= instance.OnCrouch;
                @Sprint.started -= instance.OnSprint;
                @Sprint.performed -= instance.OnSprint;
                @Sprint.canceled -= instance.OnSprint;
            }

            public void RemoveCallbacks(IMoveMapActions instance)
            {
                if (m_Wrapper.m_MoveMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMoveMapActions instance)
            {
                foreach (var item in m_Wrapper.m_MoveMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MoveMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MoveMapActions @MoveMap => new MoveMapActions(this);

        // SwitchWeapon
        private readonly InputActionMap m_SwitchWeapon;
        private List<ISwitchWeaponActions> m_SwitchWeaponActionsCallbackInterfaces = new List<ISwitchWeaponActions>();
        private readonly InputAction m_SwitchWeapon_FirstSlot;
        private readonly InputAction m_SwitchWeapon_SecondSlot;
        private readonly InputAction m_SwitchWeapon_ThirdSlot;
        private readonly InputAction m_SwitchWeapon_disarm;
        public struct SwitchWeaponActions
        {
            private @PlayerInputControl m_Wrapper;
            public SwitchWeaponActions(@PlayerInputControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @FirstSlot => m_Wrapper.m_SwitchWeapon_FirstSlot;
            public InputAction @SecondSlot => m_Wrapper.m_SwitchWeapon_SecondSlot;
            public InputAction @ThirdSlot => m_Wrapper.m_SwitchWeapon_ThirdSlot;
            public InputAction @disarm => m_Wrapper.m_SwitchWeapon_disarm;
            public InputActionMap Get() { return m_Wrapper.m_SwitchWeapon; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SwitchWeaponActions set) { return set.Get(); }
            public void AddCallbacks(ISwitchWeaponActions instance)
            {
                if (instance == null || m_Wrapper.m_SwitchWeaponActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SwitchWeaponActionsCallbackInterfaces.Add(instance);
                @FirstSlot.started += instance.OnFirstSlot;
                @FirstSlot.performed += instance.OnFirstSlot;
                @FirstSlot.canceled += instance.OnFirstSlot;
                @SecondSlot.started += instance.OnSecondSlot;
                @SecondSlot.performed += instance.OnSecondSlot;
                @SecondSlot.canceled += instance.OnSecondSlot;
                @ThirdSlot.started += instance.OnThirdSlot;
                @ThirdSlot.performed += instance.OnThirdSlot;
                @ThirdSlot.canceled += instance.OnThirdSlot;
                @disarm.started += instance.OnDisarm;
                @disarm.performed += instance.OnDisarm;
                @disarm.canceled += instance.OnDisarm;
            }

            private void UnregisterCallbacks(ISwitchWeaponActions instance)
            {
                @FirstSlot.started -= instance.OnFirstSlot;
                @FirstSlot.performed -= instance.OnFirstSlot;
                @FirstSlot.canceled -= instance.OnFirstSlot;
                @SecondSlot.started -= instance.OnSecondSlot;
                @SecondSlot.performed -= instance.OnSecondSlot;
                @SecondSlot.canceled -= instance.OnSecondSlot;
                @ThirdSlot.started -= instance.OnThirdSlot;
                @ThirdSlot.performed -= instance.OnThirdSlot;
                @ThirdSlot.canceled -= instance.OnThirdSlot;
                @disarm.started -= instance.OnDisarm;
                @disarm.performed -= instance.OnDisarm;
                @disarm.canceled -= instance.OnDisarm;
            }

            public void RemoveCallbacks(ISwitchWeaponActions instance)
            {
                if (m_Wrapper.m_SwitchWeaponActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISwitchWeaponActions instance)
            {
                foreach (var item in m_Wrapper.m_SwitchWeaponActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SwitchWeaponActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SwitchWeaponActions @SwitchWeapon => new SwitchWeaponActions(this);
        public interface IMoveMapActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnRHandAttack(InputAction.CallbackContext context);
            void OnLHandAttack(InputAction.CallbackContext context);
            void OnDelta(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
            void OnSprint(InputAction.CallbackContext context);
        }
        public interface ISwitchWeaponActions
        {
            void OnFirstSlot(InputAction.CallbackContext context);
            void OnSecondSlot(InputAction.CallbackContext context);
            void OnThirdSlot(InputAction.CallbackContext context);
            void OnDisarm(InputAction.CallbackContext context);
        }
    }
}
